#!/bin/bash
#This file goes into your ".git/hooks/" folder and will run after a pull or fetch
#assuming that the pull or fetch contains changes from your local. See https://www.kernel.org/pub/software/scm/git/docs/githooks.html

#Write the most recent tag that is reachable from a commit: https://www.kernel.org/pub/software/scm/git/docs/git-describe.html
echo $(git describe --always) > src/Version.txt
